// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['gui']['App']['DomReady'](arg1);
}

export function GetAddressesWithBalances(arg1) {
  return window['go']['gui']['App']['GetAddressesWithBalances'](arg1);
}

export function Greet(arg1) {
  return window['go']['gui']['App']['Greet'](arg1);
}
