// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {gui} from '../models';

export function DomReady(arg1:context.Context):Promise<void>;

export function GetAddressesWithBalances(arg1:string):Promise<Array<gui.balances>>;

export function Greet(arg1:string):Promise<string>;
