// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWallet(arg1) {
  return window['go']['gui']['App']['CreateWallet'](arg1);
}

export function DomReady(arg1) {
  return window['go']['gui']['App']['DomReady'](arg1);
}

export function GetAddresses(arg1) {
  return window['go']['gui']['App']['GetAddresses'](arg1);
}

export function GetAddressesWithBalances(arg1) {
  return window['go']['gui']['App']['GetAddressesWithBalances'](arg1);
}

export function GetBlockInfos(arg1) {
  return window['go']['gui']['App']['GetBlockInfos'](arg1);
}

export function GetTransactions(arg1) {
  return window['go']['gui']['App']['GetTransactions'](arg1);
}

export function Greet(arg1) {
  return window['go']['gui']['App']['Greet'](arg1);
}

export function SendTransaction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['gui']['App']['SendTransaction'](arg1, arg2, arg3, arg4, arg5);
}

export function StartNode(arg1, arg2) {
  return window['go']['gui']['App']['StartNode'](arg1, arg2);
}
